### PR TITLE
Added support of new operating systems

### PR DESCRIPTION
**Pull request by NathanFallet**
Because new kinds of servers are running on these platforms, it can be cool to show them too (instead of "Other")

### CODE REVIEW

**Comment by DoNotSpamPls** [comment]
I really **really** doubt you can run a Minecraft server on any Apple mobile OS. Correct me if I'm wrong though.

**Comment by NathanFallet** [comment]
I'm sorry for you but I'm working on this and...
IMG_9073
Screen Shot 2020-05-30 at 2 31 30 PM

**Comment by md678685** [comment]
This isn't something that I imagine will get mass adoption - I can't see anyone at all using an Apple Watch or Apple TV to run a Minecraft server, and running a server off an Android phone or iOS device is something most people would only do for the novelty of it. These stats aren't really useful for the vast majority of developers.

**Comment by PlugNCS** [comment]
This project is managed by @GroupeMINASTE and it runs flawlessly on iOS, watchOS, tvOS and of course macOS. Not only does it runs smoothly, but the power this project has allows it to run on any smart device with an incredibly low CPU and RAM consumption, as it is not developed in Java. I’m ready to bet you will soon regret using a Java Minecraft server haha

**Comment by PlugNCS** [comment]
An Apple TV as a Server makes perfect sense though, it has Gigabit Ethernet connectivity and is on the network 24/7. And having it on your phone allows you to carry a desktop-class server with you and play with your friends anywhere thanks to the Mobile Hotspot feature.

**Comment by NathanFallet** [comment]
@md678685 Even if it's not used by a lot of people, it's great to have its support integrated

**Comment by pop4959** [comment]
IMHO this is a perfect example of something that *should* be in the "Other" category. Also it doesn't seem like your server is a Bukkit or Sponge server, which is primarily what bStats tracks. Either way, why not just create your own server implementation page, and create your own breakdown of other OSes there?

**Comment by astei** [comment]
> I’m ready to bet you will soon regret using a Java Minecraft server haha

@NathanFallet @PlugNCS It's time for a reality check - you need it.

Alternative Java Edition server implementations written in programming languages other than Java have been a thing for years (Cuberite is probably the best-known - it's written in C++). You're bringing yet another implementation, this time in Swift. None of them have really achieved mass adoption. Even alternative implementations that are written in Java (such as Sponge) are far outstripped by Bukkit-derived implementations.

You do not realize the magnitude of the task you have ahead. Cuberite has had a multi-year head start, and they're nowhere close to a full server implementation. It seems you started this particular project about three weeks ago, and the current state of your project is not particularly impressive. (I could probably get just as far as you have in about three weeks if I were to use a language I'm not familiar with, perhaps much further ahead if I had a good understanding of the language I chose to work with.)

I have never worked with Swift (too busy with other stuff), so I'm not going to comment on code quality or anything (I'd be utterly unqualified to discuss such matters). But as someone who's had an interest in Minecraft server implementations, I can say with high certainty that your task ahead is hard and will be filled with major obstacles you're going to need to solve.

As for this PR - I think it's niche to include these implementations in the general OS charts. Your alternative server implementation brings almost nothing new to the table.

**Comment by PikaMug** [comment]
Really great project you've started, but I agree with the others - it's not mature enough to warrant leaving the "Other" category. Maybe if/when it achieves a following or widespread usage.

**Comment by Bastian** [comment]
Considering that there are no plugins for these kind of servers that support bStats, it would be pointless to add them to the server chart.

**Pull request closed without merging**
