### PR TITLE
Creating an author page

### PR DESCRIPTION
**Pull request by NathanFallet**
I think it could be great to have a page for authors where we can see all the plugins created by this author. Here is what I implemented:

image

### CODE REVIEW

**Comment by PikaMug** [comment]
Looks great except each author should really have their own ID number for futureproofing (desire to have duplicate names, sorting accounts by age, etc.).

**Comment by NathanFallet** [comment]
I didn't find how to retrieve a user by its ID, as I am not familiar with redis (I'm always using databases like MySQL so it's totally different to redis). I can try to explore a bit to find out how to change this, or if anyone has suggestions about it

**Comment by Bastian** [comment]
I don't think that it is necessary to include the id on this page.
Multiple users with the same name are not supported and most likely never will (e.g., because you need the name to login).

**Comment by NathanFallet** [comment]
@Bastian So is it okay like this? Or do I need to make other changes before you merge this pull request?

**Comment by Bastian** [comment]
I think it is.
I need to find some time to properly test it before merging.

**Comment by Bastian** [comment]
Thx!

**Pull request merged**
