### PR TITLE
Fix country list once and for all

### PR DESCRIPTION
**Pull request by DoNotSpamPls**
This PR builds on issue #77 and PR #99. However, I have taken a more sensible approach, which includes the following steps:
- Adding all countries listed in the [ISO 3166-1 standard](https://en.wikipedia.org/wiki/ISO_3166-1)
- Removing the country codes which have no assigned IP addresses, referencing HE's extremely useful [BGP tool](https://bgp.he.net/report/world)
- Changing some countries' names to use the name they are more commonly referred as (most people know the "Syrian Arab Republic" as Syria, for example)

Taiwan is not listed as a province of China, because it isn't. Fight me, Chinese bots.

### CODE REVIEW

**Comment by nobodxbodon** [comment]
So you are following ISO 3166 except for Taiwan? Any other exceptions?

**Comment by MiniDigger** [comment]
other stuff like Palestine from a quick glimpse.

looking good to me 👍

**Comment by md678685** [comment]
@nobodxbodon If you read the PR, you'll see the following exceptions:
* `Brunei Darussalam` is listed as `Brunei`
* `Côte d'Ivoire` is listed as `Ivory Coast`
* `Falkland Islands (the) [Malvinas]` is listed as `Falkland Islands`
* `Holy See (Vatican City State)` is listed as `Holy See`
* `Iran, Islamic Republic Of` is listed as `Iran`
* `Korea (the Democratic People's Republic of)` is listed as `North Korea`
* `Korea (the Republic of)` is listed as `South Korea`
* `Lao People's Democratic Republic (the)` is listed as `Laos`
* `Micronesia (Federated States of)` is listed as `Micronesia`
* `Palestine, State of` is listed as `Palestine`
* `Russian Federation (the)` is listed as `Russia`
* `Syrian Arab Republic (the)` is listed as `Syria`

Would you like to contest those 12 exceptions too?

**Comment by nobodxbodon** [comment]
Good to know the the total list. As I'm not familiar with ISO 3166 other than the China-related ones, at least I learnt something.

Seems Taiwan is the only one that's renamed because of your political view. It's a pity.

**Comment by Lin-Buo-Ren** [comment]
> Good to know the the total list. As I'm not familiar with ISO 3166 other than the China-related ones, at least I learnt something.
> 
> Seems Taiwan is the only one that's renamed because of your political view. It's a pity.

Hiding your true intentions under the façade of conforming well-known highly-disputed "standards" is no better.

**Comment by md678685** [comment]
@nobodxbodon I was also not familiar with ISO 3166 until yesterday. It doesn't hurt to do some research before

**Comment by nobodxbodon** [comment]
@Lin-Buo-Ren I can't believe you dare saying I'm the one who is "messing with" ISO.

Besides, if I had wanted to "hide" my political view and be "louder", I would have held private chatting rooms with my "comrades" calling for backup, like asking them to 👍 my comments [here](https://github.com/woocommerce/woocommerce/pull/24425). Oh hold on, that's **not** me.

Not to mention, who, on earth, would create a **public** repo in his own account with **English translations** in it, just to "hide" his view?

I have been pricinple and restraint in all the issues/PRs that I created related to ISO 3166 (happy to see you all along there), as I keep the political talk and my personal feelings as little as possible on my side, just want to keep the discussion as rational as possible. And now you dare distorting that and calling me a coward?

Enough is enough. Thanks to you I've seen how [this show](https://github.com/woocommerce/woocommerce/pull/24425#issuecomment-526396795) went, and I already see it just gets lower and lower here.

Stop getting personal, because that does't help anybody.

**Comment by Lin-Buo-Ren** [comment]
@nobodxbodon

Acknowledged, if you actually making constructive proposal (i.e. making the UI less politically incorrect to _ALL_ people in the world) instead of deceiving outsider project maintainers to conform to a highly-disputed standard without exceptions I would be very grateful.

**Comment by ljacqu** [comment]
Friendly reminder that the ISO-3166 is primarily here to provide standardized _abbreviations_ of countries and other geographical regions. 
Do whatever you want that makes sense but outside of following the damn abbreviations ISO-3166 quickly becomes irrelevant for inclusion and/or naming decisions.

**Pull request merged**
