### PR TITLE
use short name in ISO 3166 data

### PR DESCRIPTION
**Pull request by nobodxbodon**
https://github.com/Bastian/bStats/issues/77#issuecomment-521565517

### CODE REVIEW

**Comment by DoNotSpamPls** [comment]
Hey, while you are making a PR, I'd suggest you check with [this list](https://bgp.he.net/report/world) for any missing entries and/or names to be fixed

**Comment by nobodxbodon** [comment]
How about checking with the "English short name" field in the [ISO 3166](https://www.iso.org/obp/ui/#search/code/) list?

**Comment by nobodxbodon** [comment]
Please review the latest changes, as I've went through all the codes in the latest ISO 3166 list. Also, please advise if it's better to remove `(the)` in the name, from items like `'United States of America (the)'`

**Comment by jdh8** [comment]
This is just a duplicate pull request in part of a project that bullies Taiwanese people and requests global censorship in favor of China.
https://github.com/nobodxbodon/one-China

**Comment by Lin-Buo-Ren** [comment]
Dear maintainers(s), 

As ISO-3166 is well-known to be disputed in several sovereign state-like regions[1], especially Taiwan, I would like to urge for the rejection of this PR.

"Taiwan" is a relatively politically neutral term for, Taiwan,  "based on ISO-3166" doesn't mean one has to strictly following them.

[1] https://en.wikipedia.org/wiki/ISO_3166-1#Naming_and_disputes

**Comment by DoNotSpamPls** [comment]
Political discussions are **definetely** not welcome here, but having some insider knowledge of the situation in Taiwan, I can say that they don't think they have any sort of association with mainland China. Because of that, I don't see why this PR tries to add (Province of China) to Taiwan.

Also, please use the normal names of the countries (for example, "The Bahamas", instead of "Bahamas (the)")

**Comment by Bastian** [comment]
"Solved" in https://github.com/Bastian/bStats/pull/102

**Pull request closed without merging**
