### PR TITLE
Add Akarin Server Software

### PR DESCRIPTION
**Pull request by CirnoTH**
Akarin is a high performance fork of Tuinity.
Project URL: https://github.com/Akarin-project/Akarin

### CODE REVIEW

**Comment by MiniDigger** [comment]
Does it really make sense to add it, given the number of servers? https://bstats.org/plugin/bukkit/Torch/564

**Comment by Bastian** [comment]
Is this the same?
If I see the code correctly, they are pushing their stats to the Paper bStats page.

And given their stars on GitHub, I doubt that there are only 20 servers using it.

**Comment by MiniDigger** [comment]
thats what was linked in their readme 🤷 

edit: checked code, they push to torch, since at least a few months: https://github.com/Akarin-project/Akarin/blob/ver/1.15.2/patches/server/0005-Akarin-Metrics.patch#L17

**Comment by CirnoTH** [comment]
no, I mean add an akarin bstats instead of use torch bstats,
of course, i will pull a pr to change their bstats to akarin.

**Comment by MiniDigger** [comment]
I agree, the torch plugin should be renamed and changed to the server implementation type, I suggest the owner of the bstats plugin to join the discord and hit bastian up for how to do that.

that change isn't related to this PR tho. this PR is for the global chart, thats not related to the actual impl projects.

**Pull request closed without merging**
