### PR TITLE
Add multi line chart support

### PR DESCRIPTION
**Pull request by Phoenix616**
This adds support for multi line charts. The different lines need to be defined when creating the chart and will be tracked similarly to how the single line chart works (line names will be used instead of `0` like the single line chart in the data storage format).

### CODE REVIEW

**Comment by Phoenix616** [comment]
Any information regarding when this will be included or if there are any issues with it that need to hbe resolved? :S

**Comment by DoNotSpamPls** [comment]
Unofficial: This will likely not be merged, because Bastian is currently rewriting the bStats codebase ([backend](https://github.com/Bastian/bstats-backend) and [frontend](https://github.com/Bastian/bstats-web)). If you can rework this PR for the new backend, there is a higher chance it would be merged 😛

**Comment by Phoenix616** [comment]
Oof, that's sad to hear that I wasted my time on this seeing as this just works with the existing backend. Probably not gonna rework it seeing as the initial setup for a test environment as well as using JS was a pita :S

**Comment by Bastian** [comment]
> Oof, that's sad to hear that I wasted my time on this seeing as this just works with the existing backend.

I'm very sorry for this. At the time of this PR, I wasn't planning on the rewrite or I would have warned you.

> seeing as the initial setup for a test environment as well as using JS was a pita :S

The new code-base will most likely be much easier to work with:
1. Except Firebase, everything runs inside Docker containers. 
2. It is using TypeScript instead of plain JavaScript. TypeScript is much more pleasant to work with, especially for developers with a Java background.

**Comment by Phoenix616** [comment]
> The new code-base will most likely be much easier to work with:
> 
> 1. Except Firebase, everything runs inside Docker containers.
> 2. It is using TypeScript instead of plain JavaScript. TypeScript is much more pleasant to work with, especially for developers with a Java background.

Good to hear. Maybe I'll look into that when I find the time. :) Thanks for your continued work on this!

**Pull request closed without merging**
